In [1]:
import numpy as np
import pandas as pd

In [2]:
train_file=r'C:/Users/sr/Downloads/counterfeit_train.csv'
test_file=r'C:/Users/sr/Downloads/counterfeit_test.csv'

In [3]:
cf_train=pd.read_csv(train_file)
cf_test=pd.read_csv(test_file)

In [4]:
cf_train.head()
#cf_test.head()

Medicine_ID  Counterfeit_Weight DistArea_ID  Active_Since  Medicine_MRP  \
0       RRA15              13.100     Area046          1995      160.2366   
1       YVV26                 NaN     Area027          1983      110.4384   
2       LJC15               9.025     Area046          1995      259.4092   
3       GWC40              11.800     Area046          1995       99.9830   
4       QMN13                 NaN     Area019          1983       56.4402   

        Medicine_Type SidEffect_Level  Availability_rating  \
0        Antimalarial        critical             0.070422   
1         Mstablizers            mild             0.013000   
2             Cardiac            mild             0.060783   
3  OralContraceptives            mild             0.065555   
4       Hreplacements        critical             0.248859   

            Area_Type Area_City_Type Area_dist_level  Counterfeit_Sales  
0            DownTown         Tier 1           Small          1775.5026  
1          CityLimits         Tier 3          Medium          3069.1520  
2            DownTown         Tier 1           Small          2603.0920  
3            DownTown         Tier 1           Small          1101.7130  
4  MidTownResidential         Tier 1           Small           158.9402

In [5]:
for col in ['Medicine_ID']:
    cf_train.drop(col,1,inplace=True)
    cf_test.drop(col,1,inplace=True)

In [6]:
cf_train['Counterfeit_Weight'].fillna(cf_train['Counterfeit_Weight'].mean(),inplace=True)
cf_test['Counterfeit_Weight'].fillna(cf_test['Counterfeit_Weight'].mean(),inplace=True)

In [7]:
#cf_test['Counterfeit_Weight'].isnull().sum()
cf_test.dtypes

Counterfeit_Weight     float64
DistArea_ID             object
Active_Since             int64
Medicine_MRP           float64
Medicine_Type           object
SidEffect_Level         object
Availability_rating    float64
Area_Type               object
Area_City_Type          object
Area_dist_level         object
dtype: object

In [8]:
print(cf_train['DistArea_ID'].unique())#dummies
print(cf_train['Active_Since'].unique())
print(cf_train['Medicine_Type'].unique())
print(cf_train['SidEffect_Level'].unique())
print(cf_train['Area_Type'].unique())
print(cf_train['Active_Since'].unique())

['Area046' 'Area027' 'Area019' 'Area045' 'Area018' 'Area013' 'Area017'
 'Area010' 'Area035' 'Area049']
[1995 1983 2000 2007 1985 2005 1996 2002 1997]
['Antimalarial' 'Mstablizers' 'Cardiac' 'OralContraceptives'
 'Hreplacements' 'Antiseptics' 'Statins' 'Analgesics' 'MuscleRelaxants'
 'Antibiotics' 'Antifungal' 'Antiviral' 'Tranquilizers' 'Antacids'
 'Antipyretics' 'Stimulants']
['critical' 'mild']
['DownTown' 'CityLimits' 'MidTownResidential' 'Industrial']
[1995 1983 2000 2007 1985 2005 1996 2002 1997]


In [9]:
cf_train['SidEffect_Level']=np.where(cf_train['SidEffect_Level']=='critical',1,0).astype(int)
cf_test['SidEffect_Level']=np.where(cf_test['SidEffect_Level']=='critical',1,0).astype(int)

In [10]:
for col in ['Medicine_Type','Area_Type','Area_City_Type','Area_dist_level',"DistArea_ID"]:  
    temp=pd.get_dummies(cf_train[col],prefix=col,drop_first=True)
    cf_train=pd.concat([temp,cf_train],1)
    cf_train.drop([col],1,inplace=True)
       
    temp=pd.get_dummies(cf_test[col],prefix=col,drop_first=True)
    cf_test=pd.concat([temp,cf_test],1)
    cf_test.drop([col],1,inplace=True)

In [11]:


cf_train.head()

DistArea_ID_Area013  DistArea_ID_Area017  DistArea_ID_Area018  \
0                    0                    0                    0   
1                    0                    0                    0   
2                    0                    0                    0   
3                    0                    0                    0   
4                    0                    0                    0   

   DistArea_ID_Area019  DistArea_ID_Area027  DistArea_ID_Area035  \
0                    0                    0                    0   
1                    0                    1                    0   
2                    0                    0                    0   
3                    0                    0                    0   
4                    1                    0                    0   

   DistArea_ID_Area045  DistArea_ID_Area046  DistArea_ID_Area049  \
0                    0                    1                    0   
1                    0                    0                    0   
2                    0                    1                    0   
3                    0                    1                    0   
4                    0                    0                    0   

   Area_dist_level_Medium  ...  Medicine_Type_OralContraceptives  \
0                       0  ...                                 0   
1                       1  ...                                 0   
2                       0  ...                                 0   
3                       0  ...                                 1   
4                       0  ...                                 0   

   Medicine_Type_Statins  Medicine_Type_Stimulants  \
0                      0                         0   
1                      0                         0   
2                      0                         0   
3                      0                         0   
4                      0                         0   

   Medicine_Type_Tranquilizers  Counterfeit_Weight  Active_Since  \
0                            0           13.100000          1995   
1                            0           14.115057          1983   
2                            0            9.025000          1995   
3                            0           11.800000          1995   
4                            0           14.115057          1983   

   Medicine_MRP  SidEffect_Level  Availability_rating  Counterfeit_Sales  
0      160.2366                1             0.070422          1775.5026  
1      110.4384                0             0.013000          3069.1520  
2      259.4092                0             0.060783          2603.0920  
3       99.9830                0             0.065555          1101.7130  
4       56.4402                1             0.248859           158.9402  

[5 rows x 38 columns]

In [12]:
for col in['Counterfeit_Weight','Medicine_MRP','Availability_rating']:
    cf_train[col]=(cf_train[col]).astype(int)
    cf_test[col]=(cf_test[col]).astype(int)

In [13]:
cf_train.dtypes

DistArea_ID_Area013                   uint8
DistArea_ID_Area017                   uint8
DistArea_ID_Area018                   uint8
DistArea_ID_Area019                   uint8
DistArea_ID_Area027                   uint8
DistArea_ID_Area035                   uint8
DistArea_ID_Area045                   uint8
DistArea_ID_Area046                   uint8
DistArea_ID_Area049                   uint8
Area_dist_level_Medium                uint8
Area_dist_level_Small                 uint8
Area_dist_level_Unknown               uint8
Area_City_Type_Tier 2                 uint8
Area_City_Type_Tier 3                 uint8
Area_Type_DownTown                    uint8
Area_Type_Industrial                  uint8
Area_Type_MidTownResidential          uint8
Medicine_Type_Antacids                uint8
Medicine_Type_Antibiotics             uint8
Medicine_Type_Antifungal              uint8
Medicine_Type_Antimalarial            uint8
Medicine_Type_Antipyretics            uint8
Medicine_Type_Antiseptics       

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scalr=StandardScaler()

In [16]:
scalr.fit(cf_train)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [17]:
from sklearn.model_selection import train_test_split
cf_train1,cf_train2=train_test_split(cf_train,test_size=0.2,random_state=2)

In [18]:
x_train1=cf_train1.drop('Counterfeit_Sales',axis=1)
y_train1=cf_train1['Counterfeit_Sales']

In [19]:
x_train1.shape,y_train1.shape

((5454, 37), (5454,))

# Linear Regression

In [20]:
#beacause its a continuoes numeric o/p

In [21]:
from sklearn.linear_model import LinearRegression

In [22]:
lm=LinearRegression()

In [23]:
lm.fit(x_train1,y_train1)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [24]:
lm.intercept_

600514745415773.9

In [25]:
list(zip(x_train1.columns,lm.coef_))

[('DistArea_ID_Area013', 13649377198.13759),
 ('DistArea_ID_Area017', -1355140538759.7632),
 ('DistArea_ID_Area018', 29796718182448.906),
 ('DistArea_ID_Area019', -4263503276487.4937),
 ('DistArea_ID_Area027', 9360683229398.172),
 ('DistArea_ID_Area035', -400359484639.9716),
 ('DistArea_ID_Area045', -2890079001798.923),
 ('DistArea_ID_Area046', -1170555581527.548),
 ('DistArea_ID_Area049', 519521149711.47156),
 ('Area_dist_level_Medium', 1029573133621.4742),
 ('Area_dist_level_Small', 2105674479639.377),
 ('Area_dist_level_Unknown', 3981418611432.3135),
 ('Area_City_Type_Tier 2', 1378717751255.6506),
 ('Area_City_Type_Tier 3', -2148407404818.67),
 ('Area_Type_DownTown', 10990582369531.37),
 ('Area_Type_Industrial', -13068330333038.82),
 ('Area_Type_MidTownResidential', 10399677751695.725),
 ('Medicine_Type_Antacids', 3.6784746646881104),
 ('Medicine_Type_Antibiotics', 75.06445598602295),
 ('Medicine_Type_Antifungal', 2.6876156330108643),
 ('Medicine_Type_Antimalarial', 14.2078567743301

In [26]:
x_train2=cf_train2.drop('Counterfeit_Sales',axis=1)

In [27]:
predicted_sales=lm.predict(x_train2)

In [28]:
print(predicted_sales[:10])

[1034.875  853.5   3887.25  3673.    1261.75  2752.125 1958.375 4310.625
 2459.5   3530.375]


In [29]:
from sklearn.metrics import mean_absolute_error

In [30]:
mean_absolute_error(cf_train2['Counterfeit_Sales'],predicted_sales)

829.6509870967741

In [31]:
#We know the tentative performance now, lets build the model on entire training to make prediction on
#test/production

In [32]:
x_train=cf_train.drop('Counterfeit_Sales',axis=1) 
y_train=cf_train['Counterfeit_Sales'] 

In [33]:
lm.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [34]:
test_pred=lm.predict(cf_test)

In [35]:
test_pred

array([2809.35756814, 3939.61330441, 1441.49493867, ..., 2928.69360468,
       3853.86220864, 3742.57997111])

# Lasso

In [36]:
from sklearn.linear_model import Lasso
from sklearn.model_selection import GridSearchCV

In [37]:
params={'alpha':np.linspace(0.1,100,50)}

In [38]:
model=Lasso(fit_intercept=True)

In [39]:
grid_search=GridSearchCV(model,cv=10,param_grid=params,n_jobs=-1,verbose=10,
                         scoring='neg_mean_absolute_error')

In [40]:
grid_search.fit(x_train,y_train)

Fitting 10 folds for each of 50 candidates, totalling 500 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:   36.0s
[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:   36.3s
[Parallel(n_jobs=-1)]: Done  17 tasks      | elapsed:   36.8s
[Parallel(n_jobs=-1)]: Done  24 tasks      | elapsed:   37.1s
[Parallel(n_jobs=-1)]: Done  33 tasks      | elapsed:   37.4s
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:   37.6s
[Parallel(n_jobs=-1)]: Batch computation too fast (0.1934s.) Setting batch_size=2.
[Parallel(n_jobs=-1)]: Done  53 tasks      | elapsed:   37.8s
[Parallel(n_jobs=-1)]: Done  72 tasks      | elapsed:   38.2s
[Parallel(n_jobs=-1)]: Done  98 tasks      | elapsed:   38.7s
[Parallel(n_jobs=-1)]: Done 124 tasks      | elapsed:   39.1s
[Parallel(n_jobs=-1)]: Done 154 tasks      | elapsed:   39.6s
[Parallel(n_jobs=-1)]: Done 184 tasks      | elapsed:   40.0s
[Parallel(n_jobs=-1)]: Batch computation too fast (0.1991s.) Setting batch_size=4.
[Parallel(n_jo

GridSearchCV(cv=10, error_score='raise-deprecating',
             estimator=Lasso(alpha=1.0, copy_X=True, fit_intercept=True,
                             max_iter=1000, normalize=False, positive=False,
                             precompute=False, random_state=None,
                             selection='cyclic', tol=0.0001, warm_start=False),
             iid='warn', n_jobs=-1,
             param_grid={'alpha': array([  0.1       ,   2.13877551,   4.17755102,   6.21632653,
         8.25510204,  10.29387755,  12.332...
        57.18571429,  59.2244898 ,  61.26326531,  63.30204082,
        65.34081633,  67.37959184,  69.41836735,  71.45714286,
        73.49591837,  75.53469388,  77.57346939,  79.6122449 ,
        81.65102041,  83.68979592,  85.72857143,  87.76734694,
        89.80612245,  91.84489796,  93.88367347,  95.92244898,
        97.96122449, 100.        ])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='neg_mean_absolute_err

In [41]:
logr=grid_search.best_estimator_

In [42]:
logr.fit(x_train,y_train)

Lasso(alpha=8.255102040816327, copy_X=True, fit_intercept=True, max_iter=1000,
      normalize=False, positive=False, precompute=False, random_state=None,
      selection='cyclic', tol=0.0001, warm_start=False)

In [43]:
logr.predict(x_train)

array([2532.50166254, 3076.09308251, 4084.02450222, ..., 3054.0468423 ,
       2569.42100009, 2593.41471989])

In [44]:
mean_absolute_error(y_train,logr.predict(x_train))

823.8166717506169

In [45]:
final_test_pred=grid_search.predict(cf_test)

In [46]:
final_test_pred

array([2686.89726611, 4040.63454741, 1580.81026511, ..., 2882.80068308,
       3945.45275451, 3757.72998532])

# Decision Tree

In [47]:
params={'max_depth':[None,5,10,15,20,30,50,70],
            'min_samples_leaf':[1,2,5,10,15,20], 
            'min_samples_split':[2,5,10,15,20]
       }

In [48]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import RandomizedSearchCV

In [49]:
reg=DecisionTreeRegressor()

In [50]:
random_search=RandomizedSearchCV(reg,
                                 cv=10,
                                 param_distributions=params,
                                 scoring='neg_mean_absolute_error',
                                 n_iter=10,n_jobs=-1,verbose=20
                                    )

In [51]:
random_search.fit(x_train,y_train)

Fitting 10 folds for each of 10 candidates, totalling 100 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Batch computation too fast (0.1970s.) Setting batch_size=2.
[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done   3 tasks      | elapsed:    0.2s
[Parallel(n_jobs=-1)]: Done   4 tasks      | elapsed:    0.2s
[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    0.2s
[Parallel(n_jobs=-1)]: Done   6 tasks      | elapsed:    0.2s
[Parallel(n_jobs=-1)]: Done   7 tasks      | elapsed:    0.3s
[Parallel(n_jobs=-1)]: Done   8 tasks      | elapsed:    0.3s
[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    0.4s
[Parallel(n_jobs=-1)]: Done  12 tasks      | elapsed:    0.4s
[Parallel(n_jobs=-1)]: Done  14 tasks      | elapsed:    0.4s
[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:    0.4s
[Parallel(n_jobs=-1)]: Done  18 tasks      | elapsed:    0.6s
[Parallel(n_jobs=-1)]: Done  20 tas

RandomizedSearchCV(cv=10, error_score='raise-deprecating',
                   estimator=DecisionTreeRegressor(criterion='mse',
                                                   max_depth=None,
                                                   max_features=None,
                                                   max_leaf_nodes=None,
                                                   min_impurity_decrease=0.0,
                                                   min_impurity_split=None,
                                                   min_samples_leaf=1,
                                                   min_samples_split=2,
                                                   min_weight_fraction_leaf=0.0,
                                                   presort=False,
                                                   random_state=None,
                                                   splitter='best'),
                   iid='warn', n_iter=10, n_jobs=-1,
                   param_dis

In [52]:
def report(results, n_top=3):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Mean validation score: {0:.5f} (std: {1:.5f})".format(
                  results['mean_test_score'][candidate],
                  results['std_test_score'][candidate]))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("")

In [53]:
#The above function shows the top best_estimators

In [54]:
report(random_search.cv_results_)

Model with rank: 1
Mean validation score: -753.68445 (std: 25.28142)
Parameters: {'min_samples_split': 20, 'min_samples_leaf': 2, 'max_depth': 5}

Model with rank: 2
Mean validation score: -781.95324 (std: 26.84109)
Parameters: {'min_samples_split': 2, 'min_samples_leaf': 20, 'max_depth': 50}

Model with rank: 3
Mean validation score: -781.95324 (std: 26.84109)
Parameters: {'min_samples_split': 15, 'min_samples_leaf': 20, 'max_depth': None}

Model with rank: 3
Mean validation score: -781.95324 (std: 26.84109)
Parameters: {'min_samples_split': 2, 'min_samples_leaf': 20, 'max_depth': 20}



In [55]:
best_estimator=random_search.best_estimator_

In [56]:
best_estimator.fit(x_train,y_train)

DecisionTreeRegressor(criterion='mse', max_depth=5, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=2,
                      min_samples_split=20, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [57]:
final_pred=best_estimator.predict(cf_test)

In [58]:
final_pred

array([1979.07095   , 4055.50681309, 1590.76447225, ..., 3113.08473391,
       3476.12993231, 4055.50681309])

# Random_forest

In [60]:
param_dist = {"n_estimators":[50,100,200],
              "max_features": [2,4,5,6,8],
              "bootstrap": [True, False],
                'max_depth':[None,5,10,15,20,30,50,70],
                'min_samples_leaf':[1,2,5,10,15,20], 
                'min_samples_split':[2,5,10,15,20]
                  }

In [61]:
from sklearn.ensemble import RandomForestRegressor

In [62]:
reg=RandomForestRegressor()

In [63]:
n_iter_search = 10
random_search=RandomizedSearchCV(reg,
                                 cv=20,
                                 param_distributions=param_dist,
                                 scoring='neg_mean_absolute_error',
                                 n_iter=10,n_jobs=-1,verbose=20
                                    )

In [64]:
random_search.fit(x_train,y_train)

Fitting 20 folds for each of 10 candidates, totalling 200 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 4 concurrent workers.
[Parallel(n_jobs=-1)]: Done   1 tasks      | elapsed:    0.8s
[Parallel(n_jobs=-1)]: Done   2 tasks      | elapsed:    0.9s
[Parallel(n_jobs=-1)]: Done   3 tasks      | elapsed:    1.0s
[Parallel(n_jobs=-1)]: Done   4 tasks      | elapsed:    1.1s
[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    1.8s
[Parallel(n_jobs=-1)]: Done   6 tasks      | elapsed:    1.9s
[Parallel(n_jobs=-1)]: Done   7 tasks      | elapsed:    2.0s
[Parallel(n_jobs=-1)]: Done   8 tasks      | elapsed:    2.1s
[Parallel(n_jobs=-1)]: Done   9 tasks      | elapsed:    2.8s
[Parallel(n_jobs=-1)]: Done  10 tasks      | elapsed:    2.9s
[Parallel(n_jobs=-1)]: Done  11 tasks      | elapsed:    3.0s
[Parallel(n_jobs=-1)]: Done  12 tasks      | elapsed:    3.1s
[Parallel(n_jobs=-1)]: Done  13 tasks      | elapsed:    3.8s
[Parallel(n_jobs=-1)]: Done  14 tasks      | elapsed:    3.8s
[Parallel(n_jobs=-1)]: Done  15 tasks      | elapsed:   

[Parallel(n_jobs=-1)]: Done 132 tasks      | elapsed:   59.3s
[Parallel(n_jobs=-1)]: Done 133 tasks      | elapsed:   59.9s
[Parallel(n_jobs=-1)]: Done 134 tasks      | elapsed:  1.0min
[Parallel(n_jobs=-1)]: Done 135 tasks      | elapsed:  1.0min
[Parallel(n_jobs=-1)]: Done 136 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 137 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 138 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 139 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 140 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 141 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 142 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 143 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 144 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 145 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:  1.1min
[Parallel(n_jobs=-1)]: Done 147 tasks      | elapsed:  1.1min
[Paralle

RandomizedSearchCV(cv=20, error_score='raise-deprecating',
                   estimator=RandomForestRegressor(bootstrap=True,
                                                   criterion='mse',
                                                   max_depth=None,
                                                   max_features='auto',
                                                   max_leaf_nodes=None,
                                                   min_impurity_decrease=0.0,
                                                   min_impurity_split=None,
                                                   min_samples_leaf=1,
                                                   min_samples_split=2,
                                                   min_weight_fraction_leaf=0.0,
                                                   n_estimators='warn',
                                                   n_jobs=None, oob_score=False,
                                                   random_st...


In [65]:
report(random_search.cv_results_)

Model with rank: 1
Mean validation score: -769.81036 (std: 41.76195)
Parameters: {'n_estimators': 50, 'min_samples_split': 20, 'min_samples_leaf': 5, 'max_features': 8, 'max_depth': 20, 'bootstrap': True}

Model with rank: 2
Mean validation score: -772.99917 (std: 40.46575)
Parameters: {'n_estimators': 200, 'min_samples_split': 20, 'min_samples_leaf': 1, 'max_features': 8, 'max_depth': None, 'bootstrap': False}

Model with rank: 3
Mean validation score: -789.21578 (std: 39.49599)
Parameters: {'n_estimators': 50, 'min_samples_split': 10, 'min_samples_leaf': 1, 'max_features': 5, 'max_depth': 50, 'bootstrap': True}



In [106]:
best_estimator=random_search.best_estimator_

In [107]:
best_estimator.fit(x_train,y_train)

RandomForestRegressor(bootstrap=False, criterion='mse', max_depth=15,
                      max_features=8, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=5, min_samples_split=5,
                      min_weight_fraction_leaf=0.0, n_estimators=100,
                      n_jobs=None, oob_score=False, random_state=None,
                      verbose=0, warm_start=False)

In [108]:
final_rf_predictors=best_estimator.predict(cf_test)

In [110]:
final_rf_predictors

array([2393.3540138 , 4039.92164673, 1507.50987399, ..., 2973.81206899,
       3285.24383487, 4286.41256062])

# Gradient BOOSTing

In [66]:
!pip install xgboost

In [67]:
from sklearn.ensemble import GradientBoostingRegressor
from xgboost.sklearn import XGBRegressor

In [68]:
gbm_params={'n_estimators':[50,100,200,500,700],
           'learning_rate':[0.01,.05,0.1,0.4,0.8,1],
           'max_depth':[1,2,3,4,5],
           'subsample':[0.5,0.8],
           'max_features':[5,7,10,20,25,30,35]
           }

In [69]:
gbm=GradientBoostingRegressor()

In [70]:
random_search=RandomizedSearchCV(gbm,param_distributions=gbm_params,
                                cv=5,n_iter=20,n_jobs=-1,scoring='neg_mean_absolute_error')

In [71]:
random_search.fit(x_train,y_train)

RandomizedSearchCV(cv=5, error_score='raise-deprecating',
                   estimator=GradientBoostingRegressor(alpha=0.9,
                                                       criterion='friedman_mse',
                                                       init=None,
                                                       learning_rate=0.1,
                                                       loss='ls', max_depth=3,
                                                       max_features=None,
                                                       max_leaf_nodes=None,
                                                       min_impurity_decrease=0.0,
                                                       min_impurity_split=None,
                                                       min_samples_leaf=1,
                                                       min_samples_split=2,
                                                       min_weight_fraction_leaf=0.0,
                            

In [72]:
best_estimator=random_search.best_estimator_

In [73]:
def report(results, n_top=3):
    for i in range(1, n_top + 1):
        candidates = np.flatnonzero(results['rank_test_score'] == i)
        for candidate in candidates:
            print("Model with rank: {0}".format(i))
            print("Mean validation score: {0:.5f} (std: {1:.5f})".format(
                  results['mean_test_score'][candidate],
                  results['std_test_score'][candidate]))
            print("Parameters: {0}".format(results['params'][candidate]))
            print("")

In [74]:
report(random_search.cv_results_,5)

Model with rank: 1
Mean validation score: -750.11040 (std: 16.55125)
Parameters: {'subsample': 0.5, 'n_estimators': 700, 'max_features': 25, 'max_depth': 3, 'learning_rate': 0.01}

Model with rank: 2
Mean validation score: -753.92281 (std: 16.06846)
Parameters: {'subsample': 0.8, 'n_estimators': 200, 'max_features': 25, 'max_depth': 2, 'learning_rate': 0.05}

Model with rank: 3
Mean validation score: -760.67644 (std: 17.58740)
Parameters: {'subsample': 0.8, 'n_estimators': 500, 'max_features': 20, 'max_depth': 3, 'learning_rate': 0.05}

Model with rank: 4
Mean validation score: -761.34428 (std: 17.37316)
Parameters: {'subsample': 0.5, 'n_estimators': 700, 'max_features': 20, 'max_depth': 2, 'learning_rate': 0.05}

Model with rank: 5
Mean validation score: -768.47202 (std: 15.81696)
Parameters: {'subsample': 0.8, 'n_estimators': 700, 'max_features': 5, 'max_depth': 3, 'learning_rate': 0.05}



In [75]:
best_estimator.fit(x_train,y_train)

GradientBoostingRegressor(alpha=0.9, criterion='friedman_mse', init=None,
                          learning_rate=0.01, loss='ls', max_depth=3,
                          max_features=25, max_leaf_nodes=None,
                          min_impurity_decrease=0.0, min_impurity_split=None,
                          min_samples_leaf=1, min_samples_split=2,
                          min_weight_fraction_leaf=0.0, n_estimators=700,
                          n_iter_no_change=None, presort='auto',
                          random_state=None, subsample=0.5, tol=0.0001,
                          validation_fraction=0.1, verbose=0, warm_start=False)

In [76]:
best_estimator.predict(cf_test)

array([2298.1677021 , 4063.08976424, 1423.24160158, ..., 3017.9066189 ,
       3511.78084656, 3970.65066245])

# XG BOOST

In [87]:
xgb_params={'learning_rate':[0.01,0.05,0.1,0.3,0.5],
            'gamma':[i/10.0 for i in range(5,10)],
             'max_depth':[2,3,4,5,6,7,8],
            'min_child_weight':[1,2,5,10],
            'max_delta_step':[0,1,2,5,10],
            'subsample':[i/10.0 for i in range(5,10)],
            'colsample_bytree':[i/10.0 for i in range(5,10)],
            'colsample_bylevel':[i/10.0 for i in range(5,10)],
            'reg_lambda':[1e-5,1e-2,0.1,1,100],
            'reg_alpha':[1e-5,1e-2,0.1,1,100],
            'scale_pos_weight':[1,2,3,4,5,6,7,8,9],
            'n_estimators':[100,500,700,1000]
}

In [88]:
xgb=XGBRegressor(objective='reg:linear')

In [89]:
n_iter=10

In [90]:
random_search=RandomizedSearchCV(xgb,n_jobs=-1,cv=5,n_iter=n_iter,scoring='neg_mean_squared_error',
                                 param_distributions=xgb_params)

In [91]:
random_search.fit(x_train,y_train)

[16:53:21] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/objective/regression_obj.cu:171: reg:linear is now deprecated in favor of reg:squarederror.


RandomizedSearchCV(cv=5, error_score='raise-deprecating',
                   estimator=XGBRegressor(base_score=None, booster=None,
                                          colsample_bylevel=None,
                                          colsample_bynode=None,
                                          colsample_bytree=None, gamma=None,
                                          gpu_id=None, importance_type='gain',
                                          interaction_constraints=None,
                                          learning_rate=None,
                                          max_delta_step=None, max_depth=None,
                                          min_child_weight=None, missing=nan,
                                          monotone_con...
                                        'max_depth': [2, 3, 4, 5, 6, 7, 8],
                                        'min_child_weight': [1, 2, 5, 10],
                                        'n_estimators': [100, 500, 700, 1000],
   

In [92]:
report(random_search.cv_results_,5)

Model with rank: 1
Mean validation score: -1374428.88734 (std: 82076.32326)
Parameters: {'subsample': 0.7, 'scale_pos_weight': 8, 'reg_lambda': 1, 'reg_alpha': 100, 'n_estimators': 1000, 'min_child_weight': 2, 'max_depth': 6, 'max_delta_step': 0, 'learning_rate': 0.05, 'gamma': 0.8, 'colsample_bytree': 0.5, 'colsample_bylevel': 0.8}

Model with rank: 2
Mean validation score: -1383266.31211 (std: 84782.86761)
Parameters: {'subsample': 0.9, 'scale_pos_weight': 2, 'reg_lambda': 1e-05, 'reg_alpha': 100, 'n_estimators': 100, 'min_child_weight': 1, 'max_depth': 5, 'max_delta_step': 0, 'learning_rate': 0.3, 'gamma': 0.9, 'colsample_bytree': 0.8, 'colsample_bylevel': 0.9}

Model with rank: 3
Mean validation score: -6034454.07872 (std: 166873.31779)
Parameters: {'subsample': 0.9, 'scale_pos_weight': 7, 'reg_lambda': 1, 'reg_alpha': 0.01, 'n_estimators': 1000, 'min_child_weight': 5, 'max_depth': 5, 'max_delta_step': 5, 'learning_rate': 0.1, 'gamma': 0.5, 'colsample_bytree': 0.8, 'colsample_bylev

In [93]:
best_estimator=random_search.best_estimator_

In [94]:
best_estimator.fit(x_train,y_train)

[16:53:43] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.4.0/src/objective/regression_obj.cu:171: reg:linear is now deprecated in favor of reg:squarederror.


XGBRegressor(base_score=0.5, booster='gbtree', colsample_bylevel=0.8,
             colsample_bynode=1, colsample_bytree=0.5, gamma=0.8, gpu_id=-1,
             importance_type='gain', interaction_constraints='',
             learning_rate=0.05, max_delta_step=0, max_depth=6,
             min_child_weight=2, missing=nan, monotone_constraints='()',
             n_estimators=1000, n_jobs=4, num_parallel_tree=1,
             objective='reg:linear', random_state=0, reg_alpha=100,
             reg_lambda=1, scale_pos_weight=8, subsample=0.7,
             tree_method='exact', validate_parameters=1, verbosity=None)

In [95]:
best_estimator.predict(cf_test)

array([2589.9905, 3801.7234, 1399.9396, ..., 3204.0247, 2780.8066,
       3990.9297], dtype=float32)